AREA = 3000
STEP_SIZE = 250
USERS_THRESHOLD = 5

NUM_USERS = 850
NUM_CHROMOSOMES = 50

NUM_FIXED_MACRO = 5
NUM_MACRO = 5
NUM_MICRO = 20

FIXED_MACRO_RADIUS = 1000
MACRO_RADIUS = 1000
MICRO_RADIUS = 500

FIXED_MACRO_COST = 0
MACRO_COST = 175
MICRO_COST = 25

FIXED_MACRO_FREQ = 3.5
MACRO_FREQ = 3.5
SMALL_CELL_FREQ = 28

FIXED_MACRO_MIN_USERS = 0
MACRO_MIN_USERS = 10
MICRO_MIN_USERS = 5

FIXED_MACRO_MAX_USERS = 20
MACRO_MAX_USERS = 20
MICRO_MAX_USERS = 10

FIXED_MACRO_POWER = 40
MACRO_POWER = 40
MICRO_POWER = 40

CROSSOVER_PROBABILTY = None
MUTATION_PROBABILTY = None

CROSSOVER_METHOD = None
MUTATION_METHOD = None